# Generated by Django 5.2.10 on 2026-01-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_user_profil_name_688896_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='user_name_46b813_idx',
            old_name='user_profil_name_688896_idx',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user',
        ),
    ]
