# Generated by Django 5.2.10 on 2026-01-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_user_profil_name_688896_idx_user_name_46b813_idx_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='User',
        ),
    ]
